declare const styles: {
  readonly sidebar: string;
  readonly collapsed: string;
  readonly header: string;
  readonly countBadge: string;
  readonly list: string;
  readonly sidebarItem: string;
  readonly itemHighlighted: string;
  readonly itemFocused: string;
  readonly itemHeader: string;
  readonly priorityBadge: string;
  readonly priorityP0: string;
  readonly priorityP1: string;
  readonly priorityP2: string;
  readonly priorityP3: string;
  readonly itemName: string;
  readonly itemMeta: string;
  readonly itemAgent: string;
  readonly itemStage: string;
  readonly itemActions: string;
  readonly actionBtn: string;
  readonly approveBtn: string;
  readonly rejectBtn: string;
  readonly redirectBtn: string;
  readonly deferBtn: string;
  readonly ackBtn: string;
};
export default styles;
