fn main() {
    // Register `oauth_auth_start_url` in the app ACL manifest and keep
    // `generate_handler!` from stripping it when `removeUnusedCommands` is enabled
    // (e.g. future Tauri defaults or env). See permissions/autogenerated/.
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(&["oauth_auth_start_url"])),
    )
    .unwrap_or_else(|e| {
        eprintln!("{e:#}");
        std::process::exit(1);
    });
}
