//! Embeds GitHub/Jira OAuth app credentials at compile time.
//!
//! Loads `.env` files walking **up** from `crates/server`: **`crates/server/.env` first**, then
//! parents, **workspace root last**. Each step uses [`dotenvy::from_path_override`], so among
//! `.env` files the **repo root wins** on duplicate keys.
//!
//! Non-empty values already in the process environment **before** loading (e.g. `VAR=x cargo build`)
//! are restored afterward so the CLI still overrides `.env`.
//!
//! [`dotenvy::from_path`] is intentionally not used: it **ignores** `.env` entries when the
//! variable is already set — even to an empty string — which often breaks local builds when CI or
//! the shell exports `MOLTHUB_*=`.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    load_dotenv_chain(&manifest_dir);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("oauth_clients_embed.rs");

    let github_id = env_trim("MOLTHUB_GITHUB_CLIENT_ID").unwrap_or_default();

    let github_secret = env_trim("MOLTHUB_GITHUB_CLIENT_SECRET");

    let jira_id = env_trim("MOLTHUB_JIRA_CLIENT_ID").unwrap_or_default();

    let jira_secret = env_trim("MOLTHUB_JIRA_CLIENT_SECRET");

    let mut f = File::create(&dest).expect("write oauth_clients_embed.rs");
    writeln!(f, "// @generated by build.rs — do not edit").unwrap();
    writeln!(
        f,
        "pub const BUILT_GITHUB_CLIENT_ID: &str = {};",
        quote_str(&github_id)
    )
    .unwrap();
    match &github_secret {
        None => writeln!(
            f,
            "pub const BUILT_GITHUB_CLIENT_SECRET: Option<&'static str> = None;"
        )
        .unwrap(),
        Some(s) => writeln!(
            f,
            "pub const BUILT_GITHUB_CLIENT_SECRET: Option<&'static str> = Some({});",
            quote_str(s)
        )
        .unwrap(),
    }
    writeln!(
        f,
        "pub const BUILT_JIRA_CLIENT_ID: &str = {};",
        quote_str(&jira_id)
    )
    .unwrap();
    match &jira_secret {
        None => writeln!(
            f,
            "pub const BUILT_JIRA_CLIENT_SECRET: Option<&'static str> = None;"
        )
        .unwrap(),
        Some(s) => writeln!(
            f,
            "pub const BUILT_JIRA_CLIENT_SECRET: Option<&'static str> = Some({});",
            quote_str(s)
        )
        .unwrap(),
    }

    for key in OAUTH_ENV_KEYS {
        println!("cargo:rerun-if-env-changed={key}");
    }

    let mut dir = manifest_dir.clone();
    for _ in 0..16 {
        let dotenv = dir.join(".env");
        if dotenv.is_file() {
            println!("cargo:rerun-if-changed={}", dotenv.display());
        }
        if !dir.pop() {
            break;
        }
    }
}

const OAUTH_ENV_KEYS: &[&str] = &[
    "MOLTHUB_GITHUB_CLIENT_ID",
    "MOLTHUB_GITHUB_CLIENT_SECRET",
    "MOLTHUB_JIRA_CLIENT_ID",
    "MOLTHUB_JIRA_CLIENT_SECRET",
];

fn load_dotenv_chain(start: &Path) {
    let mut preserved: Vec<(String, String)> = Vec::new();
    for key in OAUTH_ENV_KEYS {
        if let Ok(v) = env::var(key) {
            let t = v.trim().to_owned();
            if !t.is_empty() {
                preserved.push(((*key).to_string(), t));
            }
        }
    }

    let mut dirs: Vec<PathBuf> = Vec::new();
    let mut dir = start.to_path_buf();
    for _ in 0..16 {
        dirs.push(dir.clone());
        if !dir.pop() {
            break;
        }
    }
    // Deepest (manifest dir) first, workspace root last → root `.env` wins among files.
    for d in dirs {
        let p = d.join(".env");
        if p.is_file() {
            let _ = dotenvy::from_path_override(&p);
        }
    }

    for (k, v) in preserved {
        env::set_var(&k, v);
    }
}

fn env_trim(key: &str) -> Option<String> {
    env::var(key)
        .ok()
        .map(|v| v.trim().to_owned())
        .filter(|s| !s.is_empty())
}

fn quote_str(s: &str) -> String {
    format!("{:?}", s)
}
