//! Embeds GitHub/Jira OAuth app credentials at compile time.
//!
//! Loads `.env` files walking **up** from `crates/server`, **ancestor-first** (workspace root
//! before `crates/server/`). `dotenvy` does not override existing keys, so the **first** file on
//! that path wins for each variable.

use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    load_dotenv_chain(&manifest_dir);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("oauth_clients_embed.rs");

    let default_github = "Iv23lip4ZuqkEmT9Z2U0";
    let default_jira = "3yQWy34WyjCn0wtOfawofBTMmtK3gUgs";

    let github_id = first_nonempty(&["MOLTHUB_GITHUB_CLIENT_ID", "GITHUB_CLIENT_ID"])
        .unwrap_or_else(|| default_github.to_string());

    let github_secret = first_nonempty(&["MOLTHUB_GITHUB_CLIENT_SECRET", "GITHUB_CLIENT_SECRET"]);

    let jira_id = first_nonempty(&["MOLTHUB_JIRA_CLIENT_ID", "JIRA_CLIENT_ID"])
        .unwrap_or_else(|| default_jira.to_string());

    let jira_secret = first_nonempty(&["MOLTHUB_JIRA_CLIENT_SECRET", "JIRA_CLIENT_SECRET"]);

    let mut f = File::create(&dest).expect("write oauth_clients_embed.rs");
    writeln!(f, "// @generated by build.rs — do not edit").unwrap();
    writeln!(
        f,
        "pub const BUILT_GITHUB_CLIENT_ID: &str = {};",
        quote_str(&github_id)
    )
    .unwrap();
    match &github_secret {
        None => writeln!(
            f,
            "pub const BUILT_GITHUB_CLIENT_SECRET: Option<&'static str> = None;"
        )
        .unwrap(),
        Some(s) => writeln!(
            f,
            "pub const BUILT_GITHUB_CLIENT_SECRET: Option<&'static str> = Some({});",
            quote_str(s)
        )
        .unwrap(),
    }
    writeln!(
        f,
        "pub const BUILT_JIRA_CLIENT_ID: &str = {};",
        quote_str(&jira_id)
    )
    .unwrap();
    match &jira_secret {
        None => writeln!(
            f,
            "pub const BUILT_JIRA_CLIENT_SECRET: Option<&'static str> = None;"
        )
        .unwrap(),
        Some(s) => writeln!(
            f,
            "pub const BUILT_JIRA_CLIENT_SECRET: Option<&'static str> = Some({});",
            quote_str(s)
        )
        .unwrap(),
    }

    for key in [
        "MOLTHUB_GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_ID",
        "MOLTHUB_GITHUB_CLIENT_SECRET",
        "GITHUB_CLIENT_SECRET",
        "MOLTHUB_JIRA_CLIENT_ID",
        "JIRA_CLIENT_ID",
        "MOLTHUB_JIRA_CLIENT_SECRET",
        "JIRA_CLIENT_SECRET",
    ] {
        println!("cargo:rerun-if-env-changed={key}");
    }

    let mut dir = manifest_dir.clone();
    for _ in 0..16 {
        let dotenv = dir.join(".env");
        if dotenv.is_file() {
            println!("cargo:rerun-if-changed={}", dotenv.display());
        }
        if !dir.pop() {
            break;
        }
    }
}

fn load_dotenv_chain(start: &Path) {
    let mut dirs: Vec<PathBuf> = Vec::new();
    let mut dir = start.to_path_buf();
    for _ in 0..16 {
        dirs.push(dir.clone());
        if !dir.pop() {
            break;
        }
    }
    dirs.reverse();
    for d in dirs {
        let p = d.join(".env");
        if p.is_file() {
            let _ = dotenvy::from_path(&p);
        }
    }
}

fn first_nonempty(keys: &[&str]) -> Option<String> {
    for k in keys {
        if let Ok(v) = env::var(k) {
            let t = v.trim().to_owned();
            if !t.is_empty() {
                return Some(t);
            }
        }
    }
    None
}

fn quote_str(s: &str) -> String {
    format!("{:?}", s)
}
